# First Getting the face recognition Code

### A. Loading the Model of face recognition

In [11]:
import cv2
import numpy as np
import pickle
import keras

mp = keras.models.load_model("Models/Model.keras")


# Load the face classifier
face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Load the face map for label mapping
with open("ResultsMap.pkl", 'rb') as fileReadStream:
    ResultMap = pickle.load(fileReadStream)

# Initialize the webcam
webcam = cv2.VideoCapture("Video_5.mp4")

# Function to recognize faces
def recognize_faces(frame):
    # Convert the frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect faces in the frame
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)

    for (x, y, w, h) in faces:
        # Extract the face ROI
        face_roi = frame[y:y+h, x:x+w]

        # Resize the face ROI to match the input size of the model
        resized_face = cv2.resize(face_roi, (300, 300))

        # Preprocess the face (normalize pixel values)
        normalized_face = resized_face / 255.0

        # Reshape the face for the model input (add batch dimension)
        reshaped_face = np.expand_dims(normalized_face, axis=0)

        # Perform prediction using the model
        prediction = mp.predict(reshaped_face)
        predicted_label = ResultMap[np.argmax(prediction)]
        print(prediction)
        print(predicted_label)
        print(np.max(prediction))

        if np.max(prediction) < 0.25: 
            predicted_label = 'Unknown' 

        # Draw the bounding box and label on the frame
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cv2.putText(frame, predicted_label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)

    return frame

# Main loop to capture frames from the webcam
while True:
    # Read a frame from the webcam
    ret, frame = webcam.read()
    if not ret:
        break

    # Perform face recognition on the frame
    frame = recognize_faces(frame)

    # Display the frame
    cv2.imshow('Face Recognition', frame)

    # Check for 'q' key to quit
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the webcam and close all OpenCV windows
webcam.release()
cv2.destroyAllWindows()



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step
[[0.22735101 0.23049015 0.30723032 0.2349285 ]]
Tushar
0.30723032
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
[[0.22842397 0.23996438 0.2903122  0.24129948]]
Tushar
0.2903122
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
[[0.23339973 0.2637846  0.25715137 0.24566428]]
Sairaj
0.2637846
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[0.22926648 0.24147065 0.2927727  0.23649013]]
Tushar
0.2927727
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
[[0.22858731 0.2534371  0.27214712 0.24582839]]
Tushar
0.27214712
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
[[0.23250245 0.24910252 0.2787357  0.23965931]]
Tushar
0.2787357
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
[[0.23469993 0.25975809 0.26825058 0.23729137]]
Tushar
0.26825058
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
[[0.22994106 0.24296787 0.2873292  0.23976192]]
Tushar
0.2873292
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
[[0.23058335 0.2460545  0.28304008 0.24032205]]
Tushar
0.28304008
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
[[0.23207656 0.24970926 0.276

## B. Loading the model of the action recongition

In [8]:
import keras
from keras import layers, Sequential
from keras.models import load_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import cv2
import mediapipe as mp
import glob
import pandas as pd
import numpy as np
import math
import os 


# ap = argparse.ArgumentParser()
# ap.add_argument("-m", "--model", type=str, required=True,
#                 help="path to saved .h5 model, eg: dir/model.h5")
# ap.add_argument("-c", "--conf", type=float, required=True,
#                 help="min prediction conf to detect pose class (0<conf<1)")
# ap.add_argument("-i", "--source", type=str, required=True,
#                 help="path to sample image")
# ap.add_argument("--save", action='store_true',
#                 help="Save video")

# args = vars(ap.parse_args())
source = "Running2.jpeg"
path_saved_model = "Models/Action Recognition/model.keras"
threshold = 0.2
save = "Output"
print('Hello')
##############
torso_size_multiplier = 2.5
n_landmarks = 33
n_dimensions = 3
landmark_names = [
    'nose',
    'left_eye_inner', 'left_eye', 'left_eye_outer',
    'right_eye_inner', 'right_eye', 'right_eye_outer',
    'left_ear', 'right_ear',
    'mouth_left', 'mouth_right',
    'left_shoulder', 'right_shoulder',
    'left_elbow', 'right_elbow',
    'left_wrist', 'right_wrist',
    'left_pinky_1', 'right_pinky_1',
    'left_index_1', 'right_index_1',
    'left_thumb_2', 'right_thumb_2',
    'left_hip', 'right_hip',
    'left_knee', 'right_knee',
    'left_ankle', 'right_ankle',
    'left_heel', 'right_heel',
    'left_foot_index', 'right_foot_index',
]
class_names = [
    'Running','Standing','Walking','Waving'
]
##############

mp_pose = mp.solutions.pose
pose = mp_pose.Pose()

col_names = []
for i in range(n_landmarks):
    name = mp_pose.PoseLandmark(i).name
    name_x = name + '_X'
    name_y = name + '_Y'
    name_z = name + '_Z'
    name_v = name + '_V'
    col_names.append(name_x)
    col_names.append(name_y)
    col_names.append(name_z)
    col_names.append(name_v)

# Load saved model
model = load_model(path_saved_model, compile=True)

if source.endswith(('.jpg', '.jpeg', '.png')):
    path_to_img = source
    print('Entered1')
    # Load sample Image
    
    img = cv2.imread(path_to_img)
    print(img)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    result = pose.process(img_rgb)
    if result.pose_landmarks:
        lm_list = []
        for landmarks in result.pose_landmarks.landmark:
            # Preprocessing
            max_distance = 0
            lm_list.append(landmarks)
        print('landmarks')
        print(landmarks)
        center_x = (lm_list[landmark_names.index('right_hip')].x +
                    lm_list[landmark_names.index('left_hip')].x)*0.5
        center_y = (lm_list[landmark_names.index('right_hip')].y +
                    lm_list[landmark_names.index('left_hip')].y)*0.5

        shoulders_x = (lm_list[landmark_names.index('right_shoulder')].x +
                       lm_list[landmark_names.index('left_shoulder')].x)*0.5
        shoulders_y = (lm_list[landmark_names.index('right_shoulder')].y +
                       lm_list[landmark_names.index('left_shoulder')].y)*0.5

        for lm in lm_list:
            distance = math.sqrt((lm.x - center_x)**2 + (lm.y - center_y)**2)
            if(distance > max_distance):
                max_distance = distance
        torso_size = math.sqrt((shoulders_x - center_x) **
                               2 + (shoulders_y - center_y)**2)
        max_distance = max(torso_size*torso_size_multiplier, max_distance)

        pre_lm = list(np.array([[(landmark.x-center_x)/max_distance, (landmark.y-center_y)/max_distance,
                                 landmark.z/max_distance, landmark.visibility] for landmark in lm_list]).flatten())
        data = pd.DataFrame([pre_lm], columns=col_names)
        print(data)
        predict = model.predict(data)[0]
        print('predicted')
        if max(predict) > threshold:
            pose_class = class_names[predict.argmax()]
            print('predictions: ', predict)
            print('predicted Pose Class: ', pose_class)
        else:
            pose_class = 'Unknown Pose'
            print('[INFO] Predictions is below given Confidence!!')

    # Show Result
    img = cv2.putText(
        img, f'{class_names[predict.argmax()]}',
        (40, 50), cv2.FONT_HERSHEY_PLAIN,
        2, (255, 0, 255), 2
    )

    if save:
        os.makedirs('ImageOutput', exist_ok=True)
        img_full_name = os.path.split(path_to_img)[1]
        img_name = os.path.splitext(img_full_name)[0]
        path_to_save_img = f'ImageOutput/{img_name}.jpg'
        cv2.imwrite(f'{path_to_save_img}', img)
        print(f'[INFO] Output Image Saved in {path_to_save_img}')

    cv2.imshow('Output Image', img)
    if cv2.waitKey(0) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
    print('[INFO] Inference on Test Image is Ended...')

else:
    # Web-cam
    if source.isnumeric():
        source = int(source)

    cap = cv2.VideoCapture(source)
    source_width = int(cap.get(3))
    source_height = int(cap.get(4))

    # Write Video
    if save:
        out_video = cv2.VideoWriter('output.avi', 
                            cv2.VideoWriter_fourcc(*'MJPG'),
                            10, (source_width, source_height))

    while True:
        success, img = cap.read()
        if not success:
            print('[ERROR] Failed to Read Video feed')
            break
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        result = pose.process(img_rgb)

        if result.pose_landmarks:
            lm_list = []
            for landmarks in result.pose_landmarks.landmark:
                # Preprocessing
                max_distance = 0
                lm_list.append(landmarks)
            center_x = (lm_list[landmark_names.index('right_hip')].x +
                        lm_list[landmark_names.index('left_hip')].x)*0.5
            center_y = (lm_list[landmark_names.index('right_hip')].y +
                        lm_list[landmark_names.index('left_hip')].y)*0.5

            shoulders_x = (lm_list[landmark_names.index('right_shoulder')].x +
                           lm_list[landmark_names.index('left_shoulder')].x)*0.5
            shoulders_y = (lm_list[landmark_names.index('right_shoulder')].y +
                           lm_list[landmark_names.index('left_shoulder')].y)*0.5

            for lm in lm_list:
                distance = math.sqrt((lm.x - center_x) **
                                     2 + (lm.y - center_y)**2)
                if(distance > max_distance):
                    max_distance = distance
            torso_size = math.sqrt((shoulders_x - center_x) **
                                   2 + (shoulders_y - center_y)**2)
            max_distance = max(torso_size*torso_size_multiplier, max_distance)

            pre_lm = list(np.array([[(landmark.x-center_x)/max_distance, (landmark.y-center_y)/max_distance,
                                     landmark.z/max_distance, landmark.visibility] for landmark in lm_list]).flatten())
            data = pd.DataFrame([pre_lm], columns=col_names)
            # print(data[2])
            predict = model.predict(data)[0]
            if max(predict) > threshold:
                pose_class = class_names[predict.argmax()]
                print('predictions: ', predict)
                print('predicted Pose Class: ', pose_class)
            else:
                pose_class = 'Unknown Pose'
                print('[INFO] Predictions is below given Confidence!!')

            # Show Result
            img = cv2.putText(
                img, f'{pose_class}',
                (40, 50), cv2.FONT_HERSHEY_PLAIN,
                2, (255, 0, 255), 2
            )
        # Write Video
        if save:
            out_video.write(img)

        cv2.imshow('Output Image', img)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    
    cap.release()
    if save:
        out_video.release()
        print("[INFO] Out video Saved as 'output.avi'")
    cv2.destroyAllWindows()
    print('[INFO] Inference on Videostream is Ended...')

Hello
Entered1
[[[209 203 184]
  [209 203 184]
  [210 204 185]
  ...
  [224 215 205]
  [224 215 205]
  [224 215 205]]

 [[209 203 184]
  [210 204 185]
  [210 204 185]
  ...
  [224 215 205]
  [224 215 205]
  [224 215 205]]

 [[210 204 185]
  [210 204 185]
  [210 204 185]
  ...
  [224 215 205]
  [221 212 202]
  [221 212 202]]

 ...

 [[185 183 189]
  [180 178 184]
  [153 153 159]
  ...
  [188 193 196]
  [195 201 206]
  [197 203 208]]

 [[177 175 181]
  [178 176 182]
  [165 165 171]
  ...
  [178 183 186]
  [194 200 205]
  [196 202 207]]

 [[172 170 176]
  [184 182 188]
  [189 189 195]
  ...
  [175 180 183]
  [182 188 193]
  [184 190 195]]]
landmarks
x: 0.54023635
y: 0.90556383
z: 0.2435935
visibility: 0.96696174

     NOSE_X   NOSE_Y   NOSE_Z    NOSE_V  LEFT_EYE_INNER_X  LEFT_EYE_INNER_Y  \
0 -0.216069 -0.49518 -0.54368  0.999696         -0.209308         -0.530185   

   LEFT_EYE_INNER_Z  LEFT_EYE_INNER_V  LEFT_EYE_X  LEFT_EYE_Y  ...  \
0         -0.577265          0.999476   -0.204404  

## C. Intrusion Detection code

In [14]:
# Import the required libraries
import numpy as np
import cv2
import time
import datetime
from collections import deque
from twilio.rest import Client 
import random
import heapq
import os
import matplotlib.pyplot as plt
import random
import requests


print("Libraries succesfully imported") 

Libraries succesfully imported


In [15]:


def is_person_present(frame, thresh=1100):
    kernel = None
    global foog
    
    # Apply background subtraction
    fgmask = foog.apply(frame)

    # Get rid of the shadows
    ret, fgmask = cv2.threshold(fgmask, 250, 255, cv2.THRESH_BINARY)

    # Apply some morphological operations to make sure you have a good mask
    fgmask = cv2.dilate(fgmask, kernel, iterations=4)

    # Detect contours in the frame
    contours, hierarchy = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
     
    # Check if there was a contour and the area is somewhat higher than some threshold so we know it's a person and not noise
    if contours and cv2.contourArea(max(contours, key=cv2.contourArea)) > thresh:
            
        # Get the max contour
        cnt = max(contours, key=cv2.contourArea)

        # Draw a bounding box around the person and label it as person detected
        x, y, w, h = cv2.boundingRect(cnt)
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 2)
        cv2.putText(frame, 'Person Detected', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (0, 255, 0), 1, cv2.LINE_AA)
        
        return True, frame
        
        
    # Otherwise report there was no one present
    else:
        return False, frame


def send_message(body, info_dict):

    # Your Account SID from twilio.com/console
    account_sid = info_dict['account_sid']

    # Your Auth Token from twilio.com/console
    auth_token  = info_dict['auth_token']


    client = Client(account_sid, auth_token)

    message = client.messages.create(to=info_dict['your_num'], from_=info_dict['trial_num'], body=body)





def calculate_percentage_change(frame1, frame2):
    # Convert frames to grayscale
    gray_frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    gray_frame2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    # Calculate absolute difference between the two frames
    abs_diff = cv2.absdiff(gray_frame1, gray_frame2)

    # Calculate percentage change
    percentage_change = (np.count_nonzero(abs_diff) / abs_diff.size) * 100

    return percentage_change


def save_frame(frame_heap): 
    frame_index = 0
    while frame_heap:
        # Pop the frame with the maximum percentage change (negated)
        neg_change_percentage, frame , date = heapq.heappop(frame_heap)
        change_percentage = -neg_change_percentage
        file_path = 'DetectedPerson'
        # Save the frame to disk
        cv2.imwrite(f'{file_path}/{date}.jpg', frame)
        frame_index += 1
    print("saved frame succesfully")


    


print('no error in functions')

no error in functions


## Final Code

In [ ]:
# Set Window normal so we can resize it
cv2.namedWindow('frame', cv2.WINDOW_NORMAL)

# This is a test video
cap = cv2.VideoCapture('sample_video1.mp4')

# Read the video stream from the camera
# cap = cv2.VideoCapture('http://192.168.43.1:8080/video')

# Get width and height of the frame
width = int(cap.get(3))
height = int(cap.get(4))

# Read and store the credentials information in a dict
with open('credential.txt', 'r') as myfile:
  data = myfile.read()

info_dict = eval(data)

# Initialize the background Subtractor
foog = cv2.createBackgroundSubtractorMOG2(detectShadows=True, varThreshold=100, history=2000)

# Status is True when person is present and False when the person is not present.
status = False

# After the person disappears from view, wait at least 7 seconds before making the status False
patience = 0.099

# We don't consider an initial detection unless it's detected 15 times, this gets rid of false positives
detection_thresh = 5

# Initial time for calculating if patience time is up
initial_time = None



# We are creating a deque object of length detection_thresh and will store individual detection statuses here
de = deque([False] * 10, maxlen=10)

# Initialize an empty heap to store frames along with their negated percentage change
frame_heap = []


# Initialize these variables for calculating FPS
fps = 0 
frame_counter = 0
start_time = time.time()
counter = 0

ret,prevframe = cap.read()
initial_frame = prevframe
recognisedName = ""
sent  = False

while True:
    
    ret, frame = cap.read()
    if not ret:
        break 
    
            
    # This function will return a boolean variable telling if someone was present or not, it will also draw boxes if it 
    # finds someone
    detected, annotated_image = is_person_present(frame)  
    # print(recognisedName)
    if detected and len(recognisedName) == 0: 
        # result = recogniseFromFace(frame)  
        result = ''
        if result is not None: 
            result = ''
    # Register the current detection status on our deque object
    de.appendleft(detected)
    
    # If we have consecutively detected a person 15 times then we are sure that someone is present    
    # We also make this is the first time that this person has been detected so we only initialize the videowriter once
    if sum(de) == detection_thresh and not status:                       
            status = True
            entry_time = datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")
            # out = cv2.VideoWriter('outputs/{}.mp4'.format(entry_time), cv2.VideoWriter_fourcc(*'XVID'), 15.0, (width, height))

    # If status is True but the person is not in the current frame
    if status and not detected:
        
        # Restart the patience timer only if the person has not been detected for a few frames so we are sure it wasn't a 
        # False positive
        print('i reached deepest of the darkest point')
        if sum(de) > (detection_thresh/2): 
            if initial_time is None:
                print('initial time as been setted to',initial_time)
                initial_time = time.time()
                
            
            elif initial_time is not None:        
                print('now the initial time is not null beacuse current time is ',initial_time)
                print(time.time() - initial_time)
                # If the patience has run out and the person is still not detected then set the status to False
                # Also save the video by releasing the video writer and send a text message.
                if  time.time() - initial_time >= patience:
                    status = False
                    print("inside the loop")
                    exit_time = datetime.datetime.now().strftime("%A, %I:%M:%S %p %d %B %Y")
                    # out.release()
                    # print(out)
                    initial_time = None
                    de = deque([False] * len(de))
                    body = "Alert: \nA Person Entered the Room at {} \nLeft the room at {}".format(entry_time, exit_time) 
                    if len(recognisedName) > 0: 
                        body = "Alert: {} Has entered in your Room at {} \n Left the room at {}".format(recognisedName,entry_time,exit_time)
                    print('message has been sent')
                    send_message(body, info_dict)
                    frame_index = 0
                    cv2.destroyWindow("frame")
                    while frame_heap:
                        # Pop the frame with the maximum percentage change (negated)
                        neg_change_percentage, frame , date = heapq.heappop(frame_heap)
                        change_percentage = -neg_change_percentage
                        file_path = 'DetectedPerson'
                        
                        # Save the frame to disk
                        cv2.imwrite(f'{file_path}/{date}.jpg', frame)
                        frame_index += 1
                    print("saved frame succesfully")
                    continue
                    
                
    
    # If a significant amount of detections (more than half of detection_thresh) has occurred then we reset the Initial Time.
    elif status and sum(de) > (detection_thresh/2):
        change_percentage = calculate_percentage_change(prevframe, frame)
        change_initial_change = calculate_percentage_change(initial_frame,frame)
        # print(change_percentage)
        if change_percentage > 95 and sent == False: 
            sent = True
            body = "Alert: \n Some one has changed the camera configuration at:{}".format(datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")) 
            send_message(body,info_dict)
    
        if change_initial_change > 60: 
            heapq.heappush(frame_heap, (-change_percentage, frame,datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")))
        prevframe = frame
        initial_time = None
    
    # Get the current time in the required format
    current_time = datetime.datetime.now().strftime("%A, %I:%M:%S %p %d %B %Y")

    # Display the FPS
    cv2.putText(annotated_image, 'FPS: {:.2f}'.format(fps), (510, 450), cv2.FONT_HERSHEY_COMPLEX, 0.6, (255, 40, 155), 2)
    
    # Display Time
    cv2.putText(annotated_image, current_time, (310, 20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255), 1)    
    
    # Display the Room Status
    cv2.putText(annotated_image, 'Room Occupied: {}'.format(str(status)), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, 
                (200, 10, 150), 2)

    # Show the patience Value
    if initial_time is None:
        text = 'Patience: {}'.format(patience)
    else: 
        text = 'Patience: {:.2f}'.format(max(0, patience - (time.time() - initial_time)))
        
    cv2.putText(annotated_image, text, (10, 450), cv2.FONT_HERSHEY_COMPLEX, 0.6, (255, 40, 155), 2)   

 
    # Show the Frame
    cv2.imshow('frame', frame)
    
    # Calculate the Average FPS
    frame_counter += 1
    fps = (frame_counter / (time.time() - start_time))
    
    
    # Exit if q is pressed.
    if cv2.waitKey(30) == ord('q'):
        break


# Release Capture and destroy windows
cap.release()
cv2.destroyAllWindows()

## D. Final Code Of ML

In [1]:
import pickle
from collections import Counter
import keras
import numpy as np
import cv2
import time
import datetime
from collections import deque
from twilio.rest import Client 
import random
import heapq
import os
import matplotlib.pyplot as plt
import random
import requests
import keras
from keras import layers, Sequential
from keras.models import load_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import mediapipe as mp
import glob
import pandas as pd
import math




print("Libraries succesfully imported") 

mp1 = keras.models.load_model("Models/Model.keras")


path_saved_model = "Models/Action Recognition/model.keras"
threshold = 0.2
save = "Output"
print('Hello')
##############
torso_size_multiplier = 2.5
n_landmarks = 33
n_dimensions = 3
landmark_names = [
    'nose',
    'left_eye_inner', 'left_eye', 'left_eye_outer',
    'right_eye_inner', 'right_eye', 'right_eye_outer',
    'left_ear', 'right_ear',
    'mouth_left', 'mouth_right',
    'left_shoulder', 'right_shoulder',
    'left_elbow', 'right_elbow',
    'left_wrist', 'right_wrist',
    'left_pinky_1', 'right_pinky_1',
    'left_index_1', 'right_index_1',
    'left_thumb_2', 'right_thumb_2',
    'left_hip', 'right_hip',
    'left_knee', 'right_knee',
    'left_ankle', 'right_ankle',
    'left_heel', 'right_heel',
    'left_foot_index', 'right_foot_index',
]
class_names = [
    'Running','Standing','Walking','Waving'
]


mp_pose = mp.solutions.pose
pose = mp_pose.Pose()

col_names = []
for i in range(n_landmarks):
    name = mp_pose.PoseLandmark(i).name
    name_x = name + '_X'
    name_y = name + '_Y'
    name_z = name + '_Z'
    name_v = name + '_V'
    col_names.append(name_x)
    col_names.append(name_y)
    col_names.append(name_z)
    col_names.append(name_v)

# Load saved model
model = load_model(path_saved_model, compile=True)


# Load the face classifier
face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Load the face map for label mapping
with open("ResultsMap.pkl", 'rb') as fileReadStream:
    ResultMap = pickle.load(fileReadStream)



# Function to recognize faces
def recognize_faces(frame):
    # Convert the frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Detect faces in the frame
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    predicted_label = ''
    for (x, y, w, h) in faces:
        # Extract the face ROI
        face_roi = frame[y:y+h, x:x+w]

        # Resize the face ROI to match the input size of the model
        resized_face = cv2.resize(face_roi, (300, 300))

        # Preprocess the face (normalize pixel values)
        normalized_face = resized_face / 255.0

        # Reshape the face for the model input (add batch dimension)
        reshaped_face = np.expand_dims(normalized_face, axis=0)

        # Perform prediction using the model
        prediction = mp1.predict(reshaped_face)
        predicted_label = ResultMap[np.argmax(prediction)]
        print(prediction)
        print(predicted_label)
        print(np.max(prediction))

        if np.max(prediction) < 0.25: 
            predicted_label = 'Unknown' 

        # Draw the bounding box and label on the frame
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cv2.putText(frame, predicted_label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    return predicted_label , frame


def recognisize_pose(frame): 
    img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    result = pose.process(img_rgb)
    activity = ''
    if result.pose_landmarks:
        lm_list = []
        for landmarks in result.pose_landmarks.landmark:
            # Preprocessing
            max_distance = 0
            lm_list.append(landmarks)
        # print('landmarks')
        # print(landmarks)
        center_x = (lm_list[landmark_names.index('right_hip')].x +
                    lm_list[landmark_names.index('left_hip')].x)*0.5
        center_y = (lm_list[landmark_names.index('right_hip')].y +
                    lm_list[landmark_names.index('left_hip')].y)*0.5

        shoulders_x = (lm_list[landmark_names.index('right_shoulder')].x +
                       lm_list[landmark_names.index('left_shoulder')].x)*0.5
        shoulders_y = (lm_list[landmark_names.index('right_shoulder')].y +
                       lm_list[landmark_names.index('left_shoulder')].y)*0.5

        for lm in lm_list:
            distance = math.sqrt((lm.x - center_x)**2 + (lm.y - center_y)**2)
            if(distance > max_distance):
                max_distance = distance
        torso_size = math.sqrt((shoulders_x - center_x) **
                               2 + (shoulders_y - center_y)**2)
        max_distance = max(torso_size*torso_size_multiplier, max_distance)

        pre_lm = list(np.array([[(landmark.x-center_x)/max_distance, (landmark.y-center_y)/max_distance,
                                 landmark.z/max_distance, landmark.visibility] for landmark in lm_list]).flatten())
        data = pd.DataFrame([pre_lm], columns=col_names)
        # print(data)
        predict = model.predict(data)[0]
        print('predicted')
        activity = class_names[predict.argmax()]
        if max(predict) > threshold:
            pose_class = class_names[predict.argmax()]
            print('predictions: ', predict)
            print('predicted Pose Class: ', pose_class)
        else:
            pose_class = 'Unknown Pose'
            print('[INFO] Predictions is below given Confidence!!')

        frame = cv2.putText(
                frame, f'{class_names[predict.argmax()]}',
                (40, 50), cv2.FONT_HERSHEY_PLAIN,
                2, (255, 0, 255), 2
        )
    
    print('[INFO] Inference on Test Image is Ended...')
    return activity 



def is_person_present(frame, thresh=1100):
    kernel = None
    global foog
    
    # Apply background subtraction
    fgmask = foog.apply(frame)

    # Get rid of the shadows
    ret, fgmask = cv2.threshold(fgmask, 250, 255, cv2.THRESH_BINARY)

    # Apply some morphological operations to make sure you have a good mask
    fgmask = cv2.dilate(fgmask, kernel, iterations=4)

    # Detect contours in the frame
    contours, hierarchy = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
     
    # Check if there was a contour and the area is somewhat higher than some threshold so we know it's a person and not noise
    if contours and cv2.contourArea(max(contours, key=cv2.contourArea)) > thresh:
            
        # Get the max contour
        cnt = max(contours, key=cv2.contourArea)

        # Draw a bounding box around the person and label it as person detected
        x, y, w, h = cv2.boundingRect(cnt)
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 2)
        cv2.putText(frame, 'Person Detected', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (0, 255, 0), 1, cv2.LINE_AA)
        
        return True, frame
        
        
    # Otherwise report there was no one present
    else:
        return False, frame


def send_message(body, info_dict):

    # Your Account SID from twilio.com/console
    account_sid = info_dict['account_sid']

    # Your Auth Token from twilio.com/console
    auth_token  = info_dict['auth_token']


    client = Client(account_sid, auth_token)

    message = client.messages.create(to=info_dict['your_num'], from_=info_dict['trial_num'], body=body)





def calculate_percentage_change(frame1, frame2):
    # Convert frames to grayscale
    gray_frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    gray_frame2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    # Calculate absolute difference between the two frames
    abs_diff = cv2.absdiff(gray_frame1, gray_frame2)

    # Calculate percentage change
    percentage_change = (np.count_nonzero(abs_diff) / abs_diff.size) * 100

    return percentage_change


def save_frame(frame_heap): 
    frame_index = 0
    while frame_heap:
        # Pop the frame with the maximum percentage change (negated)
        neg_change_percentage, frame , date = heapq.heappop(frame_heap)
        change_percentage = -neg_change_percentage
        file_path = 'DetectedPerson'
        # Save the frame to disk
        cv2.imwrite(f'{file_path}/{date}.jpg', frame)
        frame_index += 1
    print("saved frame succesfully")

print('no error in functions')


Libraries succesfully imported
Hello
no error in functions


In [2]:
# Set Window normal so we can resize it
cv2.namedWindow('frame', cv2.WINDOW_NORMAL)

# This is a test video
cap = cv2.VideoCapture('http://192.168.43.1:8080/video')

# Read the video stream from the camera
# cap = cv2.VideoCapture('http://192.168.43.1:8080/video')

# Get width and height of the frame
width = int(cap.get(3))
height = int(cap.get(4))

# Read and store the credentials information in a dict
with open('credential.txt', 'r') as myfile:
  data = myfile.read()

info_dict = eval(data)

# Initialize the background Subtractor
foog = cv2.createBackgroundSubtractorMOG2(detectShadows=True, varThreshold=100, history=2000)

# Status is True when person is present and False when the person is not present.
status = False

# After the person disappears from view, wait at least 7 seconds before making the status False
patience = 0.099

# We don't consider an initial detection unless it's detected 15 times, this gets rid of false positives
detection_thresh = 5

# Initial time for calculating if patience time is up
initial_time = None



# We are creating a deque object of length detection_thresh and will store individual detection statuses here
de = deque([False] * 10, maxlen=10)

# Initialize an empty heap to store frames along with their negated percentage change
frame_heap = []


# Initialize these variables for calculating FPS
fps = 0 
frame_counter = 0
start_time = time.time()
counter = 0

ret,prevframe = cap.read()
initial_frame = prevframe
recognisedName = ""
sent  = False
activity = []

while True:
    
    ret, frame = cap.read()
    if not ret:
        break 
    
            
    # This function will return a boolean variable telling if someone was present or not, it will also draw boxes if it 
    # finds someone
    detected, annotated_image = is_person_present(frame)  
    # print(recognisedName)
    # print('Hello')
    

    if detected and len(recognisedName) == 0: 
        # result = recogniseFromFace(frame)  
        print('inside block')
        result = recognize_faces(frame)  
        # print(result)
        activties = recognisize_pose(frame)
        # print(activties)
        activity.append(activties) 
        name , frame = result
        print('inside block')
        if name is not None: 
            if name: 
                recognisedName = name 
            else: 
                recognisedName = ""
    # Register the current detection status on our deque object
    de.appendleft(detected)
    
    # If we have consecutively detected a person 15 times then we are sure that someone is present    
    # We also make this is the first time that this person has been detected so we only initialize the videowriter once
    if sum(de) == detection_thresh and not status:                       
            status = True
            entry_time = datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")
            # out = cv2.VideoWriter('outputs/{}.mp4'.format(entry_time), cv2.VideoWriter_fourcc(*'XVID'), 15.0, (width, height))

    # If status is True but the person is not in the current frame
    if status and not detected:
        
        # Restart the patience timer only if the person has not been detected for a few frames so we are sure it wasn't a 
        # False positive
        print('i reached deepest of the darkest point')
        if sum(de) > (detection_thresh/2): 
            if initial_time is None:
                print('initial time as been setted to',initial_time)
                initial_time = time.time()
                
            
            elif initial_time is not None:        
                print('now the initial time is not null beacuse current time is ',initial_time)
                print(time.time() - initial_time)
                # If the patience has run out and the person is still not detected then set the status to False
                # Also save the video by releasing the video writer and send a text message.
                if  time.time() - initial_time >= patience:
                    status = False
                    print("inside the loop")
                    exit_time = datetime.datetime.now().strftime("%A, %I:%M:%S %p %d %B %Y")
                    # out.release()
                    # print(out)
                    initial_time = None
                    de = deque([False] * len(de))
                    element_counts = Counter(activity)
                    
                    # Find the most common element
                    most_common_element = element_counts.most_common(1)[0][0]
                    body = "Alert: \nA Person Entered the Room at {} \nLeft the room at {} and did ".format(entry_time, exit_time,most_common_element) 
                    # Use Counter to count occurrences of each element
                    activity.clear()
                    if len(recognisedName) > 0: 
                        body = "Alert: {} Has entered in your Room at {} \n Left the room at {} and did {}".format(recognisedName,entry_time,exit_time, most_common_element)
                    print('message has been sent')
                    send_message(body, info_dict)
                    frame_index = 0
                    cv2.destroyWindow("frame")
                    while frame_heap:
                        # Pop the frame with the maximum percentage change (negated)
                        neg_change_percentage, frame , date = heapq.heappop(frame_heap)
                        change_percentage = -neg_change_percentage
                        file_path = 'DetectedPerson'
                        
                        # Save the frame to disk
                        cv2.imwrite(f'{file_path}/{date}.jpg', frame)
                        frame_index += 1
                    print("saved frame succesfully")
                    continue
                    
                
    
    # If a significant amount of detections (more than half of detection_thresh) has occurred then we reset the Initial Time.
    elif status and sum(de) > (detection_thresh/2):
        change_percentage = calculate_percentage_change(prevframe, frame)
        change_initial_change = calculate_percentage_change(initial_frame,frame)
        # print(change_percentage)
        if change_percentage > 95 and sent == False: 
            sent = True
            body = "Alert: \n Some one has changed the camera configuration at:{}".format(datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")) 
            if recognisedName != 'Unknown': 
                body = "Alert: \n {} has changed the camera configuration at:{}".format(recognisedName, datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")) 
            send_message(body,info_dict)
    
        if change_initial_change > 60: 
            heapq.heappush(frame_heap, (-change_percentage, frame,datetime.datetime.now().strftime("%A, %I-%M-%S %p %d %B %Y")))
        prevframe = frame
        initial_time = None
    
    # Get the current time in the required format
    current_time = datetime.datetime.now().strftime("%A, %I:%M:%S %p %d %B %Y")

    # Display the FPS
    cv2.putText(annotated_image, 'FPS: {:.2f}'.format(fps), (510, 450), cv2.FONT_HERSHEY_COMPLEX, 0.6, (255, 40, 155), 2)
    
    # Display Time
    cv2.putText(annotated_image, current_time, (310, 20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255), 1)    
    
    # Display the Room Status
    cv2.putText(annotated_image, 'Room Occupied: {}'.format(str(status)), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, 
                (200, 10, 150), 2)

    # Show the patience Value
    if initial_time is None:
        text = 'Patience: {}'.format(patience)
    else: 
        text = 'Patience: {:.2f}'.format(max(0, patience - (time.time() - initial_time)))
        
    cv2.putText(annotated_image, text, (10, 450), cv2.FONT_HERSHEY_COMPLEX, 0.6, (255, 40, 155), 2)   

 
    # Show the Frame
    cv2.imshow('frame', frame)
    
    # Calculate the Average FPS
    frame_counter += 1
    fps = (frame_counter / (time.time() - start_time))
    
    
    # Exit if q is pressed.
    if cv2.waitKey(30) == ord('q'):
        break


# Release Capture and destroy windows
cap.release()
cv2.destroyAllWindows()

inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
inside block
[INFO] Inference on Test Image is Ended...
inside block
i reached deepest of the darkest point
initial time as been setted to None
i reached deepest of the dar